// source https://fr.wikipedia.org/wiki/Num%C3%A9ro_postal_d%27acheminement

const npa = [
    [1, "Suisse romande sud"],
    [10, "Lausanne, Échallens"],
    [11, "Morges, Rolle"],
    [12, "Canton de Genève, canton de Vaud"],
    [13, "Massif du Jura : Cossonay, Orbe, Vallorbe"],
    [14, "Yverdon-les-Bains, Estavayer-le-Lac"],
    [15, "Moudon, Lucens, Avenches"],
    [16, "Romont, Bulle"],
    [17, "Fribourg et région du lac de Morat"],
    [175, "Sarine Ouest"],
    [1752, "Villars-sur-Glâne"],
    [1753, "Matran"],
    [1754, "Avry-sur-Matran, Rosé"],
    [172, "Sarine Sud"],
    [1723, "Marly"],
    [1724, "Commune du Mouret et Ferpicloz"],
    [173, "Gruyère Nord"],
    [1734, "La Roche"],
    [18, "Est du lac Léman : Vevey, Montreux, Chablais vaudois : Aigle, Monthey, Saint-Maurice"],
    [19, "Martigny, Sion"],
    [2, "Suisse romande nord"],
    [20, "Neuchâtel"],
    [21, "Val-de-Travers"],
    [22, "Val-de-Ruz"],
    [23, "La Chaux-de-Fonds, district des Franches-Montagnes"],
    [24, "Le Locle, La Sagne"],
    [25, "Bienne, région du lac de Bienne, Granges"],
    [26, "région de Saint-Imier"],
    [27, "Jura bernois : Tavannes, Tramelan, Moutier"],
    [28, "Delémont"],
    [29, "Ajoie : Porrentruy"],
    [3, "Berne et Valais supérieur"],
    [30, "ville de Berne et périphérie"],
    [31, "sud de Berne"],
    [32, "Seeland : Aarberg, Anet, Chiètres, Lyss"],
    [33, "zone entre Berne et Soleure"],
    [34, "Berthoud et Haute-Argovie sauf Langenthal"],
    [35, "Emmental"],
    [36, "Thoune"],
    [37, "Spiez, Simmental"],
    [38, "Interlaken, Haslital"],
    [39, "Valais : Sierre, Crans-Montana"],
    [4, "Région de Bâle"],
    [40, "ville de Bâle"],
    [41, "vallée de Leimen, vallée de Birs, Riehen, Bettingen, Pratteln"],
    [42, "vallée de Laufon, Dornach, Thierstein"],
    [43, "vallée de Frick : Rheinfelden, Stein"],
    [44, "Canton de Bâle-Campagne"],
    [45, "Soleure"],
    [46, "Olten"],
    [47, "Oensingen, Balsthal"],
    [48, "Zofingue"],
    [49, "Langenthal"],
    [5, "Région d’Aarau"],
    [50, "Ville d'Aarau et périphérie, ouest de la vallée de Frick : Frick et Laufenburg"],
    [51, "Möriken-Wildegg, Schinznach-Dorf, Schinznach-Bad"],
    [52, "Brugg, vallée de Mettau"],
    [53, "Turgi, Koblenz"],
    [54, "Baden, Wettingen"],
    [55, "Mellingen"],
    [56, "Lenzburg, Wohlen, Bremgarten, Muri"],
    [57, "District de Kulm, Beinwil am See, Kölliken, Safenwil"],
    [6, "Centre de la Suisse, canton du Tessin"],
    [60, "Lucerne, canton d'Obwald"],
    [61, "Entlebuch, Willisau"],
    [62, "Sempach, Sursee, Hochdorf"],
    [63, "Canton de Zoug, canton de Nidwald"],
    [64, "Canton de Schwytz sans les districts de March et de Höfe, Uri"],
    [65, "Bellinzone, Mesocco, Val Calanca"],
    [66, "Locarno, Vallemaggia, Val Verzasca"],
    [67, "District de Léventine, Valle di Blenio"],
    [68, "Mendrisiotto"],
    [69, "Lugano"],
    [7, "Grisons"],
    [70, "Coire, Arosa, Domat/Ems, Flims"],
    [71, "Région de Surselva"],
    [72, "Prättigau, Davos"],
    [73, "Région de Landquart, Sargans"],
    [74, "Région d'Albula"],
    [75, "Engadine, Val Müstair"],
    [76, "Val Bregaglia"],
    [77, "Val Poschiavo"],
    [8, "Région de Zurich"],
    [80, "Ville de Zurich. Les deux derniers chiffres indiquent la circonscription de la ville ou le bureau distributeur : 8005 Zurich 5 pour la 5e circonscription ou 8031 Zurich 31 pour le bureau distributeur n°31)"],
    [81, "nord-ouest du canton de Zurich"],
    [82, "Schaffhouse, Kreuzlingen"],
    [83, "Kloten, Hinwil, sud du canton de Thurgovie"],
    [84, "Winterthour, vallée de la Töss"],
    [85, "Frauenfeld, Weinfelden, Amriswil, Romanshorn"],
    [86, "Dübendorf"],
    [87, "rive droite du lac de Zurich, canton de Glaris"],
    [88, "rive gauche du lac de Zurich, districts de March et de Höfe et circonscription électorale de Sarganserland"],
    [89, "vallée de la Limmat, Albis (de), district d'Affoltern"],
    [9, "Est de la Suisse et Liechtenstein"],
    [90, "Saint-Gall, Appenzell"],
    [91, "Herisau"],
    [92, "Gossau, Flawil, Uzwil, Bischofszell"],
    [93, "Arbon"],
    [94, "Rorschach, vallée du Rhin, Liechtenstein"],
    [95, "Wil"],
    [96, "Toggenburg"],
]

